apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: my-expense
  labels:
    app: html
    tier: web
    project: expense
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: html
      tier: web
      project: expense
  template:
    metadata:
      labels:
        app: html
        tier: web
        project: expense
    spec:
      containers:
      - name: frontend
        image: sunil0428/frontend:v1
        
---
apiVersion: v1
kind: Service
metadata: 
  name: frontend
  namespace: my-expense
spec:
  type: LoadBalancer
  selector:
    app: html
    tier: web
    project: expense
  ports:
  - name: frontend-service-port
    protocol: TCP
    port: 80
    targetPort: 80