apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: my-expense
  labels:
    app: html
    tier: web
    project: expense
spec:
  # modify replicas according to your case
  selector:
    matchLabels:
      app: html
      tier: web
      project: expense
  template:
    metadata:
      labels:
        app: html
        tier: web
        project: expense
    spec:
      containers:
      - name: frontend
        image: joindevops/frontend:v1
        resources:
          requests:
            memory: "32Mi"     # Minimum amount of memory the container will need
            cpu: "125m"        # Minimum amount of CPU the container will need
          limits:
            memory: "32Mi"    # Maximum amount of memory the container can use
            cpu: "125m"
---
apiVersion: v1
kind: Service
metadata: 
  name: frontend
  namespace: my-expense
spec:
  type: LoadBalancer
  selector:
    app: html
    tier: web
    project: expense
  ports:
  - name: frontend-service-port
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-app-hpa
  namespace: my-expense
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  minReplicas: 1
  maxReplicas: 10
