apiVersion: v1
kind: ConfigMap
metadata: 
  name: backend
  namespace: my-expense
data: 
  DB_HOST: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: my-expense
  labels:
    app: nodejs
    tier: backend
    project: expense
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
    app: nodejs
    tier: backend
    project: expense
  template:
    metadata:
      labels:
        app: nodejs
        tier: backend
        project: expense
    spec:
      containers:
      - name: backend
        image: sunil0428/backend:v1
        envFrom:
        - configMapRef:
            name: backend

---
apiVersion: v1
kind: Service
metadata: 
  name: backend
  namespace: my-expense
spec:
  selector:
    app: nodejs
    tier: backend
    project: expense
  ports:
  - name: backend-service-port
    protocol: TCP
    port: 8080
    targetPort: 8080